# Generated by Django 4.1.7 on 2023-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
